- name: apt update
  hosts: all
  tasks:   
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: 'yes'
        cache_valid_time: 86400 #One day
    - name: Cleanup
      apt:
        autoclean: yes