- hosts: all
  gather_facts: True
  vars_files:
    - "roles/user/vars/all_users.yml"
  vars:
    users:
     - "{{all_users.thies}}"
     - "{{all_users.strifel}}"
     - "{{all_users.jadyn}}"
     - "{{all_users.hanno}}"
     - "{{all_users.pajowu}}"
     - "{{all_users.m4schini}}"
  roles:
    - role: user
