galaxy_info:
  author: AlpakaInfraCrew
  description: Install pretalx

  license: MIT

  min_ansible_version: "2.9"

  platforms:
    - name: Debian
      versions:
        - all

  galaxy_tags: []

dependencies: []
